### ISSUE TITLE
vector3.multiply calculation error.

### ISSUE THREAD

**Issue by SKSON** [dotnet/dotnet-api-docs.ko-kr#1]
Two identical vector3 crossproduct result should be {0.0.0} but the results are not correct.

vec1 {&lt;0.5507279, 0.5769531, 0.6031782&gt;} vec2 {&lt;0.5507279, 0.5769531, 0.6031782&gt;}
vec3 = vector3.multiply(vec1, vec2)
vec2 should be {0,0,0}
but, the result is {&lt;0.3033012, 0.3328748, 0.363824&gt;}

and many error happened.
my code is as below.

and I tested other library, such as rhino.geometry.vector3f,
and the crossproduct results of two identical vectors are all {0, 0, 0}

Imports System.Numerics
Module Module1

    Sub Main()
        Dim max As Integer = 30
        Dim rv(max - 1) As Vector3
        Dim lv(max - 1) As Vector3

        Dim i As Integer
        For i = 0 To max - 1
            rv(i).X = i
            rv(i).Y = i + 1
            rv(i).Z = i + 2
            rv(i) = Vector3.Normalize(rv(i))
            lv(i) = rv(i)  ' now, all of the lv() and rv() vector3 array is same.
        Next
        Dim cs(max - 1) As Vector3
        For i = 0 To max - 1
            cs(i) = Vector3.Multiply(rv(i), lv(i))
            If rv(i) &lt;&gt; lv(i) Then
                MsgBox("error")
            End If
            If cs(i).X &lt;&gt; 0 Or cs(i).Y &lt;&gt; 0 Or cs(i).Z &lt;&gt; 0 Then
                MsgBox("error")
            End If
        Next
    End Sub
End Module

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 28889f50-97bd-36c4-4446-6d8c6d24b402
* Version Independent ID: 6e7fa75c-4a26-395f-668b-97e2a6ecc464
* Content: [Vector3.Multiply Method (System.Numerics)](https://docs.microsoft.com/ko-kr/dotnet/api/system.numerics.vector3.multiply?view=netframework-4.7.2)
* Content Source: [xml/System.Numerics/Vector3.xml](https://github.com/dotnet/dotnet-api-docs.ko-kr/blob/live/xml/System.Numerics/Vector3.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mikedn** [comment]
You say cross product but your code does vector multiplication:
```
cs(i) = Vector3.Multiply(rv(i), lv(i))
```
If you do use the [cross product](https://docs.microsoft.com/ko-kr/dotnet/api/system.numerics.vector3.cross?view=netframework-4.7.2) then your program runs fine.

**Comment by CeciAc** [comment]
Hello, @mikedn 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
