### ISSUE TITLE
반대로 해석

### ISSUE THREAD

**Issue by ararion** [dotnet/dotnet-api-docs.ko-kr#3]
Span<T> is a ref struct that is allocated on the stack rather than on the managed heap.
Span<T> ref 구조체 스택에 아닌 관리 되는 힙에 할당 되는 합니다. =>
Span<T>는 ref 구조체로 관리 되는 힙이 아닌 스택에 할당됩니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 36ef14f5-5cfc-5d83-971f-18789cf45237
* Version Independent ID: 9aa52936-b378-8715-4b31-46a1c0974c43
* Content: [Span&lt;T&gt; Struct (System)](https://docs.microsoft.com/ko-kr/dotnet/api/system.span-1?view=netcore-2.2)
* Content Source: [xml/System/Span`1.xml](https://github.com/dotnet/dotnet-api-docs.ko-kr/blob/live/xml/System/Span`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hello, @ararion 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @ararion 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/api/system.span-1?view=netcore-2.2 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
