### ISSUE TITLE
String.EndsWith()의 반환 값 설명이 잘못 번역된 것 같습니다.

### ISSUE THREAD

**Issue by highfence** [dotnet/dotnet-api-docs.ko-kr#4]
[여기에 피드백 입력]
이 문자열의 끝이 true 매개 변수와 일치하면 value이고, 그러지 않으면 false입니다.
-> 이 문자열의 끝이 value 매개 변수와 일치하면 true이고, 그러지 않으면 false입니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8e545671-a89c-c707-65fb-459bfe6fbdc0
* Version Independent ID: ffa683cf-2f20-25cd-1998-8f2a202525d1
* Content: [String.EndsWith Method (System)](https://docs.microsoft.com/ko-kr/dotnet/api/system.string.endswith?view=netframework-4.7.2)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs.ko-kr/blob/live/xml/System/String.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
안녕하세요. , @highfence 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @highfence 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/api/system.string.endswith?view=netframework-4.7.2 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
