### ISSUE TITLE
Button Set IsCancel Property true

### ISSUE THREAD

**Issue by zudbs** [dotnet/dotnet-api-docs.ko-kr#6]
[여기에 피드백 입력]
If I Set IsCancel Protperty true in Button
CommandParameter is null

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 29c051ec-55a8-8bc8-9a6c-39b612a71cd2
* Version Independent ID: ee7c5afc-8ad9-a758-68ac-8b4bd404f714
* Content: [Button.IsCancel Property (System.Windows.Controls)](https://docs.microsoft.com/ko-kr/dotnet/api/system.windows.controls.button.iscancel?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls/Button.xml](https://github.com/dotnet/dotnet-api-docs.ko-kr/blob/live/xml/System.Windows.Controls/Button.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @zudbs 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback/제품 피드백 제공" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
